# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 593674fa16fa3bb8d36e0e86ce07cb237e8058e20fea248885497f21379dbe57f7924ec79bd646a93af9c671ba8b61eb90b6fd140c80cbed58625566068d3ac2

test:
  secret_key_base: 82fb9bb9cc94f9fb8c7a171d76683aa6513e3c5998208f3dcc86d4e68ce8c2b63077bed38eded0addb80b395df4164aee93e3fae943ce26f145882b710f273dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
